[global]
metric = 120
msgSize = 25
log = 4

[timers]
updateTimer = 30
timeoutTimer = 180
garbageTimer = 120

[interfaces]
 [interfaces.br0]
  [interfaces.br0.keychain]
   authType = 3
   authKey = "123"
 [interfaces.lo]
  passive = true

 [neighbors]
  [neighbors."192.168.90.1"]
   [neighbors."192.168.90.1".keychain]
    authType = 3
    authKey = "123"